name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies and prebuild
      run: |
        npm install --legacy-peer-deps
        npx expo prebuild --platform android
        
    - name: Build APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: agent-finance-app
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
