name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Prebuild Android project
      run: npx expo prebuild --platform android
      
    - name: Build Debug APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Find and Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: agent-finance-app-debug
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
        
    - name: Build Release APK (إذا أردت)
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --stacktrace
      continue-on-error: true
      
    - name: Upload Release APK (إذا نجح)
      uses: actions/upload-artifact@v3
      with:
        name: agent-finance-app-release
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 30
      if: success()
